{{- if and (eq "bucketrepo" .Values.jxRequirements.repository) .Values.istio.enabled }}
apiVersion: {{ .Values.istio.apiVersion }}
kind: VirtualService
metadata:
  name: bucketrepo
spec:
  gateways:
{{- if .Values.istio.createGateway }}
  - jx-gateway
{{- else }}
  - {{ .Values.istio.gateway.name }}
{{- end }}
  hosts:
    - bucketrepo{{ .Values.jxRequirements.ingress.namespaceSubDomain }}{{ .Values.jxRequirements.ingress.domain }}
  http:
  - route:
    - destination:
        host: bucketrepo
      weight: 100
{{- end }}