{{- if and (eq "bucketrepo" .Values.jxRequirements.repository) (not .Values.istio.enabled) }}
apiVersion: {{ .Values.ingress.apiVersion | default "networking.k8s.io/v1" }}
kind: Ingress
metadata:
  annotations:
{{- template "ingressAnnotations" . }}
  name: bucketrepo
spec:
  rules:
  - http:
      paths:
{{- if eq .Values.ingress.apiVersion "networking.k8s.io/v1beta1" }}
      - backend:
          serviceName: bucketrepo
          servicePort: 80
{{- else }}
      - pathType: {{ .Values.ingress.pathType | default "ImplementationSpecific" }}
        backend:
          service:
            name: bucketrepo
            port:
              number: 80
{{- end }}
{{- if eq "NodePort" .Values.jxRequirements.ingress.serviceType }}
        path: "/bucketrepo"
{{- else if .Values.ingress.customHosts.bucketrepo }}
        path: "/"
    host: {{ .Values.ingress.customHosts.bucketrepo }}
{{- else if .Values.jxRequirements.ingress.domain }}
        path: "/"
    host: {{ .Values.ingress.prefix.bucketrepo }}{{ .Values.jxRequirements.ingress.namespaceSubDomain }}{{ .Values.jxRequirements.ingress.domain }}
{{- end }}
{{- if .Values.jxRequirements.ingress.tls.enabled }}
  tls:
  - hosts:
  {{- if .Values.ingress.customHosts.bucketrepo }}
    - {{ .Values.ingress.customHosts.bucketrepo }}
  {{- else }}
    - {{ .Values.ingress.prefix.bucketrepo }}{{ .Values.jxRequirements.ingress.namespaceSubDomain }}{{ .Values.jxRequirements.ingress.domain }}
  {{- end }}
{{- if .Values.bucketrepo.ingress.tls.secretName }}
    secretName: "{{ .Values.bucketrepo.ingress.tls.secretName }}"
{{- else if .Values.jxRequirements.ingress.tls.secretName }}
    secretName: "{{ .Values.jxRequirements.ingress.tls.secretName }}"
{{- else if .Values.jxRequirements.ingress.tls.production }}
    secretName: "tls-{{ .Values.jxRequirements.ingress.domain | replace "." "-" }}-p"
{{- else }}
    secretName: "tls-{{ .Values.jxRequirements.ingress.domain | replace "." "-" }}-s"
{{- end }}
{{- end }}
{{- end }}