{{- if and (or (eq "lighthouse" .Values.jxRequirements.webhook) (eq "prow" .Values.jxRequirements.webhook)) .Values.istio.enabled }}
apiVersion: {{ .Values.istio.apiVersion }}
kind: VirtualService
metadata:
  name: hook
spec:
  gateways:
{{- if .Values.istio.createGateway }}
  - jx-gateway
{{- else }}
  - {{ .Values.istio.gateway.name }}
{{- end }}
  hosts:
    - hook{{ .Values.jxRequirements.ingress.namespaceSubDomain }}{{ .Values.jxRequirements.ingress.domain }}
  http:
  - route:
    - destination:
        host: hook
      weight: 100
{{- end }}