{{- if eq .Values.lighthouseEngine "tekton" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name:  {{ .Values.pipeline.serviceAccount.name | default "tekton-bot" | quote }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name:  {{ .Values.pipeline.serviceAccount.name | default "tekton-bot" | quote }}
subjects:
- kind: ServiceAccount
  name:  {{ .Values.pipeline.serviceAccount.name | default "tekton-bot" | quote }}
  namespace: {{ .Release.Namespace }}
{{- end -}}
