{{ if .Values.chartmuseumServiceLink.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: jenkins-x-chartmuseum
  labels:
    app: chartmuseum
    release: jenkins-x
    jenkins.io/credentials-type: usernamePassword
  annotations:
    jenkins.io/credentials-keybinding-password: BASIC_AUTH_PASS
    jenkins.io/credentials-keybinding-username: BASIC_AUTH_USER
type: Opaque
data:
{{- range $name, $value := .Values.chartmuseum.env.secret }}
{{- if not (empty $value) }}
  {{ $name }}: {{ $value | b64enc }}
{{- end }}
{{- end }}
{{- end }}