apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gcpods
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: gcpods
subjects:
  - kind: ServiceAccount
    name: jx-gcpods
    namespace: {{ .Release.Namespace }}
