{{- if .Values.secrets.kanikoSecret }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: kaniko-secret
  annotations:
    # Workaround until Kubernetes Credentials Provider can deal with a secret without annotations.
    jenkins.io/from-chart: jxboot-helmfile-resources
  labels:
    jenkins.io/credentials-type: secretText
data:
  kaniko-secret: {{ .Values.secrets.kanikoSecret.Data | b64enc | quote }}
{{- end }}
