{{- if eq "local" .Values.jxRequirements.secretStorage }}
apiVersion: v1
kind: Secret
metadata:
  name: jx-local-secrets
type: Opaque
data:
  secrets.yaml: {{ printf "secrets:\n%s" (toYaml .Values.secrets | indent 2) | b64enc | quote }}
{{- end }}
