apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: jenkins-maven-settings
data:
{{- if .Values.secrets.mavenSettings }}
  settings.xml: {{ .Values.secrets.mavenSettings| b64enc | quote }}
{{- else }}
  settings.xml: ""
{{- end }}
{{- if .Values.secrets.mavenSettings }}
  settings-security.xml: {{ .Values.secrets.mavenSettings | b64enc | quote }}
{{- end }}
