{{- if .Values.secrets.tektonBucket }}
apiVersion: v1
data:
  json: {{ .Values.secrets.tektonBucket | b64enc | quote }}
kind: Secret
metadata:
  annotations:
    # Workaround until Kubernetes Credentials Provider can deal with a secret without annotations.
    jenkins.io/foo: bar
  labels:
    jenkins.io/credentials-type: secretText
  name: tekton-artifact-bucket
type: Opaque
{{- end }}
