{{- if eq .Values.lighthouseEngine "tekton" }}
apiVersion: v1
data:
  .dockerconfigjson: {{ .Values.pipeline.auth.docker.configJson | b64enc | quote }}
kind: Secret
metadata:
  name: tekton-container-registry-auth
  annotations:
    tekton.dev/docker-0: {{ .Values.pipeline.auth.docker.url | quote }}
  labels:
    app.kubernetes.io/component: webhook
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tekton-pipelines
    secret.jenkins-x.io/replica-source: "true"
type: kubernetes.io/dockerconfigjson
{{- end -}}
